# IMPORTANT: The version must match the version of docker-compose.yml
---
version: '2.3'

# The following override shows an example for the cockroachdb
services:
  # Your custom Docker image here:
  php:
    restart: always
    build: ./images/php${PHP_SERVER}
  mysql:
    restart: always
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
  httpd:
    restart: always
